name: "Godot Engine"
on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - released

env:
  GODOT_VERSION: 3.6.2
  EXPORT_NAME: rota-ci

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Cache Godot Engine downloads
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: |
            export/godot
            export/editor_data/export_templates/${{ env.GODOT_VERSION }}.stable
          key: godot-${{ env.GODOT_VERSION }}

      - name: Download Godot Engine from GitHub release
        id: download
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          mkdir -p export && cd export

          # Download Godot Engine itself
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip && \
          unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip && \
          mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 godot

          # Download export templates
          mkdir -p editor_data/export_templates
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz && \
          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz && \
          mv templates editor_data/export_templates/${GODOT_VERSION}.stable

      - name: Export PCK file
        run: |
          # Tell Godot Engine to be self-contained
          touch export/._sc_

          export/godot --no-window --path=. --export-pack "Linux/X11" export/${EXPORT_NAME}.pck

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ env.EXPORT_NAME }}
          path: export/${{ env.EXPORT_NAME }}.pck

  release:
    name: Release
    needs: export
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: ${{ env.EXPORT_NAME }}

      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mv '${{ env.EXPORT_NAME }}.pck' '${{ env.EXPORT_NAME }}-${{ github.ref_name }}.pck'
          gh release upload '${{ github.ref_name }}' '${{ env.EXPORT_NAME }}-${{ github.ref_name }}.pck' --repo '${{ github.repository }}'
